backend: openai-chat
base-url: http://localhost:901
endpoint: /v1/chat/completions

model: Qwen3.6-35B-A3B
tokenizer: /home/yrlab/models/llm/weights_local/Qwen3.6-35B-A3B-FP8

dataset-name: random
num-prompts: 50
input-len: 4096
output-len: 1024

max-concurrency: 4
request-rate: inf

env:
  OPENAI_API_KEY: sk-123
